"""Added api

Revision ID: 702df3dab5e5
Revises: 5266f18a4c87
Create Date: 2024-10-06 21:01:29.453279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702df3dab5e5'
down_revision = '5266f18a4c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    # ### end Alembic commands ###
